import CustomLayout from "components/open-part/custom-layout"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CustomLayout>
          {children}
        </CustomLayout>
      </body>
    </html>
  )
}
