import CustomLayout from "components/open-part/custom-layout"
import '@mantine/core/styles.css';
import Providers from "./providers";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>StarLine</title>
      </head>
      <body>
        <CustomLayout>
          <Providers>
            {children}
          </Providers>
        </CustomLayout>
      </body>
    </html>
  )
}
